// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  Sentence = 2,
  SentenceContent = 3,
  Atom = 4,
  AtomString = 5,
  AtomNumber = 6,
  Predicate = 7,
  Alias = 8,
  Filler = 9,
  FullStop = 10
