// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QVQPOOOOQO'#C`'#C`OOQO'#Ch'#ChOhQPO'#C_OoQPO'#C^OOQO'#Cg'#CgQVQPOOOOQO-E6f-E6fOOQO,58x,58xOOQO-E6e-E6e",
  stateData: "t~O_OS~OTPOUPOVQOWQOXQO~OYRX~PVOYWO~O",
  goto: "x]PP^bfPPPPPPkqTTOUTSOUVQORUQUORXUSROURVR",
  nodeNames: "⚠ Document Sentence SentenceContent Atom AtomString AtomNumber Predicate Alias Filler FullStop",
  maxTerm: 15,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "%V~RbX^!Zpq!Zst#Owx#jz{$O!O!P$j!Q![$o!c!}$w#R#S$w#T#o$w#y#z!Z$f$g!Z#BY#BZ!Z$IS$I_!Z$I|$JO!Z$JT$JU!Z$KV$KW!Z&FU&FV!Z~!`Y_~X^!Zpq!Z#y#z!Z$f$g!Z#BY#BZ!Z$IS$I_!Z$I|$JO!Z$JT$JU!Z$KV$KW!Z&FU&FV!Z~#RR!c!}#[#R#S#[#T#o#[~#aRW~!c!}#[#R#S#[#T#o#[~#mQwx#s#Q#R#j~#xQT~wx#s#Q#R#j~$RR!c!}$[#R#S$[#T#o$[~$aRV~!c!}$[#R#S$[#T#o$[~$oOY~~$tPU~!Q![$o~$|RX~!c!}$w#R#S$w#T#o$w",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
